import React, { useEffect, useState } from 'react';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Loader2, Download, Save, AlertTriangle, CheckCircle, XCircle, FileText } from "lucide-react";
import { base44 } from '@/api/base44Client';
import { runFullAssessment } from '@/components/scoring/scoringEngine';
import ScoreGauge from '@/components/ui/ScoreGauge';
import RiskBadge from '@/components/ui/RiskBadge';
import { cn } from "@/lib/utils";

export default function StepResults({ data, counterparty, user, onResultsCalculated, onSave }) {
  const [results, setResults] = useState(null);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    const calculated = runFullAssessment(data, counterparty);
    setResults(calculated);
    onResultsCalculated?.(calculated);
  }, [data, counterparty]);

  const handleSave = async () => {
    if (!results || saving) return;
    
    setSaving(true);
    try {
      const assessment = await base44.entities.Assessment.create({
        org_id: user.org_id,
        counterparty_id: counterparty.id,
        counterparty_name: counterparty.name,
        assessor_email: user.email,
        inputs: data,
        computed_metrics: results.computed_metrics,
        component_scores: results.component_scores,
        total_score: results.total_score,
        risk_band: results.risk_band,
        hard_stop_flag: results.hard_stop_flag,
        hard_stop_reason: results.hard_stop_reason,
        reasons: results.reasons,
        recommended_actions: results.recommended_actions
      });
      
      setSaved(true);
      setSaving(false);
      
      // Delay navigation slightly to show saved state
      setTimeout(() => {
        onSave?.(assessment);
      }, 300);
    } catch (error) {
      console.error('Failed to save assessment:', error);
      setSaving(false);
    }
  };

  const generatePDF = () => {
    // Create printable content
    const content = `
KYC CREDIT CONFIDENCE ASSESSMENT
================================

Counterparty: ${counterparty.name}
UEN: ${counterparty.uen || 'Not provided'}
Assessment Date: ${new Date().toLocaleDateString()}
Assessor: ${user.email}

OVERALL SCORE: ${results.total_score}/100
RISK BAND: ${results.risk_band.toUpperCase()}
${results.hard_stop_flag ? `\n⚠️ HARD STOP: ${results.hard_stop_reason}` : ''}

COMPONENT SCORES
----------------
Singapore Presence: ${results.component_scores.sg_presence}/30
Ownership & Control: ${results.component_scores.ownership}/30
Financial Health: ${results.component_scores.financial}/40
Red Flags: ${results.component_scores.red_flags}/10

SCORING BREAKDOWN
-----------------
${results.reasons.join('\n')}

RECOMMENDED ACTIONS
-------------------
${results.recommended_actions.map((a, i) => `${i + 1}. ${a}`).join('\n')}

---
Generated by KYC Confidence (SG)
    `.trim();

    // Create and download text file (for simplicity)
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `KYC_Assessment_${counterparty.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (!results) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="w-8 h-8 animate-spin text-emerald-600" />
      </div>
    );
  }

  const componentBars = [
    { label: 'SG Presence', score: results.component_scores.sg_presence, max: 30, color: 'bg-blue-500' },
    { label: 'Ownership', score: results.component_scores.ownership, max: 30, color: 'bg-purple-500' },
    { label: 'Financial', score: results.component_scores.financial, max: 40, color: 'bg-emerald-500' },
    { label: 'Red Flags', score: results.component_scores.red_flags, max: 10, color: 'bg-amber-500' }
  ];

  return (
    <div className="space-y-6">
      {/* Main Score */}
      <Card className={cn(
        "border-2",
        results.hard_stop_flag 
          ? "border-red-300 bg-red-50"
          : results.risk_band === 'green' 
          ? "border-emerald-200 bg-emerald-50/50"
          : results.risk_band === 'amber'
          ? "border-amber-200 bg-amber-50/50"
          : "border-red-200 bg-red-50/50"
      )}>
        <CardContent className="pt-6">
          <div className="flex flex-col md:flex-row items-center gap-8">
            <div className="flex-shrink-0">
              {results.hard_stop_flag ? (
                <div className="w-40 h-40 rounded-full bg-red-100 flex items-center justify-center">
                  <XCircle className="w-20 h-20 text-red-600" />
                </div>
              ) : (
                <ScoreGauge score={results.total_score} size="lg" />
              )}
            </div>
            <div className="flex-1 text-center md:text-left">
              <h2 className="text-2xl font-bold text-slate-900 mb-2">
                Credit Confidence Score
              </h2>
              <div className="mb-4">
                <RiskBadge band={results.risk_band} showDescription size="lg" />
              </div>
              {results.hard_stop_flag && (
                <div className="flex items-center gap-2 text-red-700 bg-red-100 rounded-lg px-4 py-2">
                  <AlertTriangle className="w-5 h-5" />
                  <span className="font-medium">{results.hard_stop_reason}</span>
                </div>
              )}
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Component Breakdown */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Score Breakdown</CardTitle>
          <CardDescription>Performance across assessment components</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {componentBars.map(bar => (
            <div key={bar.label} className="space-y-1">
              <div className="flex justify-between text-sm">
                <span className="text-slate-600">{bar.label}</span>
                <span className="font-medium">{bar.score}/{bar.max}</span>
              </div>
              <div className="h-3 bg-slate-100 rounded-full overflow-hidden">
                <div 
                  className={cn("h-full rounded-full transition-all duration-500", bar.color)}
                  style={{ width: `${(bar.score / bar.max) * 100}%` }}
                />
              </div>
            </div>
          ))}
        </CardContent>
      </Card>

      {/* Top Reasons */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Key Scoring Factors</CardTitle>
          <CardDescription>Top reasons impacting the score</CardDescription>
        </CardHeader>
        <CardContent>
          <ul className="space-y-2">
            {results.reasons.slice(0, 8).map((reason, i) => (
              <li key={i} className="flex items-start gap-2 text-sm">
                {reason.startsWith('+') ? (
                  <CheckCircle className="w-4 h-4 text-emerald-500 mt-0.5 flex-shrink-0" />
                ) : reason.startsWith('-') ? (
                  <XCircle className="w-4 h-4 text-red-500 mt-0.5 flex-shrink-0" />
                ) : (
                  <div className="w-4 h-4 rounded-full bg-slate-200 mt-0.5 flex-shrink-0" />
                )}
                <span className="text-slate-700">{reason}</span>
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>

      {/* Recommended Actions */}
      {results.recommended_actions.length > 0 && (
        <Card className="border-amber-200 bg-amber-50/50">
          <CardHeader>
            <CardTitle className="text-base flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 text-amber-600" />
              Recommended Actions
            </CardTitle>
            <CardDescription>Steps to mitigate identified risks</CardDescription>
          </CardHeader>
          <CardContent>
            <ol className="space-y-3">
              {results.recommended_actions.map((action, i) => (
                <li key={i} className="flex items-start gap-3">
                  <span className="w-6 h-6 bg-amber-100 text-amber-700 rounded-full flex items-center justify-center text-sm font-medium flex-shrink-0">
                    {i + 1}
                  </span>
                  <span className="text-slate-700 text-sm">{action}</span>
                </li>
              ))}
            </ol>
          </CardContent>
        </Card>
      )}

      {/* Actions */}
      <div className="flex flex-col sm:flex-row gap-3 justify-end">
        <Button variant="outline" onClick={generatePDF}>
          <Download className="w-4 h-4 mr-2" />
          Export Report
        </Button>
        <Button 
          onClick={handleSave}
          disabled={saving || saved}
          className={cn(
            saved 
              ? "bg-emerald-100 text-emerald-700 hover:bg-emerald-100"
              : "bg-emerald-600 hover:bg-emerald-700"
          )}
        >
          {saving ? (
            <>
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              Saving...
            </>
          ) : saved ? (
            <>
              <CheckCircle className="w-4 h-4 mr-2" />
              Saved
            </>
          ) : (
            <>
              <Save className="w-4 h-4 mr-2" />
              Save Assessment
            </>
          )}
        </Button>
      </div>
    </div>
  );
}